### PR TITLE
Support custom fade animation duration and easing

### PR DESCRIPTION
**Pull request by kkak10**
Hi! this library is very useful. but not change duration and easing animation.

so i create PR for change duration and easing. 

thank you :)

### CODE REVIEW

**Comment by Swizec** [comment]
First PR! 😱

Thank you, looks great.

Adding your example to the example page as well.

**Comment by kkak10** [comment]
@Swizec Thank you :) 

I think we'd better develop some more test codes. Because we don't have a test code right now.

What do you think about?

**Comment by Swizec** [comment]
You are correct @kkak10, having tests would be great. I've been using the demo page to test :)

If you want to take a crack at adding some tests, go ahead.

**Comment by kkak10** [comment]
@Swizec I would like to contribute to this project.

I'll try to write the test code.

**Pull request merged**
